### ISSUE TITLE
log4cplus-2.0.6 tests fail to compile with recent glibc >= 2.34

### ISSUE THREAD

**Issue by tgurr** [log4cplus/log4cplus#519]
Your bundled catch version causes tests to not compile on systems with glibc >= 2.34, e.g. Fedora Rawhide:

```
[...]
In file included from /usr/x86_64-pc-linux-gnu/include/signal.h:328,
                 from ./catch/single_include/catch2/catch.hpp:8034,
                 from src/global-init.cxx:27:
./catch/single_include/catch2/catch.hpp:10822:58: error: call to non-'constexpr' function 'long int sysconf(int)'
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/x86_64-pc-linux-gnu/include/bits/sigstksz.h:24,
                 from /usr/x86_64-pc-linux-gnu/include/signal.h:328,
                 from ./catch/single_include/catch2/catch.hpp:8034,
                 from src/global-init.cxx:27:
/usr/x86_64-pc-linux-gnu/include/unistd.h:641:17: note: 'long int sysconf(int)' declared here
  641 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from src/global-init.cxx:27:
./catch/single_include/catch2/catch.hpp:10881:45: error: size of array 'altStackMem' is not an integral constant-expression
10881 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |
[...]
```

Upstream fix: https://github.com/catchorg/Catch2/commit/c0d0a50bdb2ae2f749443c0386c2b25379bdbf76

Also, provide the following information:

 - version: 2.0.6
 - operating system, CPU, bitness: Linux 64bit
 - `configure` script, or CMake, etc., flags and settings: ./configure --enable-unit-tests
 - flags and settings used by your application: -
 - compiler and its version: gcc (GCC) 10.3.0

**Comment by wilx** [comment]
Please test the 2.0.7 release.
