### ISSUE TITLE
Latest master C++23 check fails even though C++23 is supported

### ISSUE THREAD

**Issue by jdmdmm** [log4cplus/log4cplus#639]
When trying to build the latest master, the cmake fails due to no support of C++23, even though C++23 is supported and used elsewhere in our code.

Also, provide the following information:

 - version: master
 - operating system, CPU, bitness: *what are your environement's OS, CPU's, and platform's characteristics*
 Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

 - `configure` script, or CMake, etc., flags and settings: cmake / make with no flags, following standard build instructions that have always worked in the past
 - flags and settings used by your application: n/a
 - compiler and its version: 
 Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Ubuntu 13.2.0-23ubuntu4)

gcc -v --help 2> /dev/null | sed -n '/^ *-std=\([^<][^ ]\+\).*/ {s//\1/p}'
f2003
f2008
f2008ts
f2018
f95
gnu
legacy
c++03
c++0x
c++11
c++14
c++17
c++1y
c++1z
c++20
c++23
c++2a
c++2b
c++98
c11
c17
c18
c1x
c2x
c89
c90
c99
c9x
gnu++03
gnu++0x
gnu++11
gnu++14
gnu++17
gnu++1y
gnu++1z
gnu++20
gnu++23
gnu++2a
gnu++2b
gnu++98
gnu11
gnu17
gnu18
gnu1x
gnu2x
gnu89
gnu90
gnu99
gnu9x
iso9899:1990
iso9899:199409
iso9899:1999
iso9899:199x
iso9899:2011
iso9899:2017
iso9899:2018

**Comment by wilx** [comment]
How does this issue manifest? Do you have a log file that shows it that you could attach or put on Gist?

**Comment by jdmdmm** [comment]
having run cmake which works fine, I then run make and I eventually get this:
...
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking whether g++ supports C++23 features by default... no
checking whether g++ supports C++23 features with -std=gnu++23... no
checking whether g++ supports C++23 features with -std=gnu++2b... no
checking whether g++ supports C++23 features with -std=c++23... no
checking whether g++ supports C++23 features with +std=c++23... no
checking whether g++ supports C++23 features with -h std=c++23... no
checking whether g++ supports C++23 features with -std=c++2b... no
checking whether g++ supports C++23 features with +std=c++2b... no
checking whether g++ supports C++23 features with -h std=c++2b... no
configure: error: *** A compiler with support for C++23 language features is require

**Comment by wilx** [comment]
I don't understand how you are using it. Are you building log4cplus via the Automake build system? If so, why not use the CMake build that is also available directly?

**Comment by wilx** [comment]
> `configure: error: *** A compiler with support for C++23 language features is require`

The `configure` script should work in recent versions of master branch. I can see it works GitHub action that was last executed:

```
checking whether g++-14 supports C++23 features by default... no
checking whether g++-14 supports C++23 features with -std=gnu++23... yes
```

**Comment by jdmdmm** [comment]
Using a standard build as above:

```
FetchContent_Declare(project_log4cplus
	PREFIX log4cplus
	GIT_REPOSITORY https://github.com/log4cplus/log4cplus.git
	GIT_TAG master
	GIT_REMOTE_UPDATE_STRATEGY REBASE_CHECKOUT
)

FetchContent_MakeAvailable(project_log4cplus)
```

We now get this:

```
[ 64%] Built target log4cplusS
[ 64%] Building CXX object _deps/project_log4cplus-build/simpleserver/CMakeFiles/loggingserverS.dir/loggingserver.cxx.o
[ 64%] Linking CXX executable ../bin/loggingserverS
/usr/bin/ld: ../src/liblog4cplusS.a(catch_amalgamated.cpp.o): in function `main':
/xxx/xxx/xxx/buildtest1/_deps/project_log4cplus-src/catch/extras/catch_amalgamated.cpp:4776: multiple definition of `main'; CMakeFiles/loggingserverS.dir/loggingserver.cxx.o:/xxx/xxx/xxx/buildtest1/_deps/project_log4cplus-src/simpleserver/loggingserver.cxx:231: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [_deps/project_log4cplus-build/simpleserver/CMakeFiles/loggingserverS.dir/build.make:99: _deps/project_log4cplus-build/bin/loggingserverS] Error 1
make[1]: *** [CMakeFiles/Makefile2:4543: _deps/project_log4cplus-build/simpleserver/CMakeFiles/loggingserverS.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

I would have thought that this would build on its own, are we missing some options?

**Comment by wilx** [comment]
I have pushed a fix for this. Pull from master and try again, please.

**Comment by jdmdmm** [comment]
This seems to have build, but I notice that you have BUILD_SHARED_LIBS set to ON by default - is there a way to switch this to OFF so that we can have static libs when using:

```
FetchContent_Declare(project_log4cplus
	PREFIX log4cplus
	GIT_REPOSITORY https://github.com/log4cplus/log4cplus.git
	GIT_TAG master
	GIT_REMOTE_UPDATE_STRATEGY REBASE_CHECKOUT
)

FetchContent_MakeAvailable(project_log4cplus)
```

**Comment by jdmdmm** [comment]
Actually having said that it seems that a static lib was produced anyway:

`./_deps/project_log4cplus-build/src/liblog4cplusS.a`

**Comment by wilx** [comment]
You set CMake options on command line via, e.g., `-DBUILD_SHARED_LIBS=OFF`.

**Comment by jdmdmm** [comment]
May I ask, why has it built:
`./_deps/project_log4cplus-build/src/liblog4cplusS.a`
and not:
`./_deps/project_log4cplus-build/src/liblog4cplus.a`

Do I need another option?
As this will require changing a bunch of CMakeList.txt files on our side to work now
Thanks

**Comment by jdmdmm** [comment]
Thank you - our of interest what is the decoration for / it's meaning in this context?

**Comment by wilx** [comment]
There is `S` for static library and `U` for a variant with `wchar_t` instead of `char` in API. The reason is that there are platforms like Windows that implement import libraries can look like a static library. Similarly, on AIX shared libraries have the same `.a` extension as static libraries. By decorating the library file name with `S` it makes them unambiguous and you can also install both shared and static libraries at the same time on all platforms.

**Comment by jdmdmm** [comment]
Thank you so much for your help, everything is building perfectly now.
Just have to run the tests

**Comment by jdmdmm** [comment]
Quick question:
How do I enable lto in the cmake build system for log4cpp? I see there's an ac option but I can't see a cmake one
